services:
  db:
    image: postgres:16
    container_name: postgres_certificado
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - certificadonm-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_certificado
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - certificadonm-network
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  app-dev:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: spring_certificado_dev
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      SPRING_URL: ${SPRING_URL}
      SPRING_USERNAME: ${SPRING_USERNAME}
      SPRING_PASSWORD: ${SPRING_PASSWORD}
    volumes:
      - ./pom.xml:/app/pom.xml
      - ./src:/app/src
      - ./target:/app/target
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - certificadonm-network
    profiles: ["dev"]

  app:
    build: .
    container_name: spring_certificado
    environment:
      SPRING_URL: ${SPRING_URL}
      SPRING_USERNAME: ${SPRING_USERNAME}
      SPRING_PASSWORD: ${SPRING_PASSWORD}
    depends_on:
      - db
    restart: always
    networks:
      - certificadonm-network
    ports:
      - "8080:8080"
    profiles: ["prod"]

networks:
  certificadonm-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
